const n=v=>{const x=Number(String(v??'').replace(/[$,]/g,''));return Number.isFinite(x)&&x>=0?x:null};
const money=v=>v==null?null:`$${Number(v).toFixed(2)}`;
export function purchaseAffordability({availableCash,purchaseAmount,upcomingExpenses=0,safetyBuffer=0}={}){const a=n(availableCash),p=n(purchaseAmount),u=n(upcomingExpenses)||0,b=n(safetyBuffer)||0;if(a==null||p==null)return{tool:'purchase_affordability',status:'insufficient_information'};const spend=+(a-u).toFixed(2),remain=+(spend-p).toFixed(2);const status=spend<p?'not_affordable':remain-b<0?'affordable_but_tight':'affordable';return{tool:'purchase_affordability',status,availableCash:a,purchaseAmount:p,upcomingExpenses:u,safetyBuffer:b,spendableAfterUpcomingExpenses:spend,remainingAfterPurchase:remain,recommendation:status==='not_affordable'?`I would not make the purchase; you would be ${money(Math.abs(remain))} short.`:`The purchase leaves ${money(remain)} after upcoming expenses.`};}
export function saveMeMoney({category='purchase',amount,frequency='monthly',situation,goal,urgency='normal',availableCash,purchaseAmount,upcomingExpenses=0,safetyBuffer=0}={}){const a=n(amount),m={weekly:52/12,biweekly:26/12,monthly:1,quarterly:1/3,yearly:1/12,one_time:0}[frequency]??1,monthlyCost=a==null?null:+(a*m).toFixed(2);return{tool:'save_me_money',category,currentAmount:a,frequency,monthlyCost,annualCost:monthlyCost==null?null:+(monthlyCost*12).toFixed(2),situation:situation||null,goal:goal||null,urgency,affordability:(availableCash!==undefined||purchaseAmount!==undefined)?purchaseAffordability({availableCash,purchaseAmount:purchaseAmount??amount,upcomingExpenses,safetyBuffer}):null,nextSteps:['Compare the all-in price.','Ask for an itemized quote.','Look for a lower-cost equivalent.','Ask what would make the seller lower the price.']};}
export function secondOpinion({decision,options=[],priorities=[],concerns=[]}={}){return{tool:'second_opinion',decision:decision||null,options,priorities,concerns,checklist:['Strongest reason to do it?','Strongest reason not to?','What important fact is unknown?','What would change the recommendation?']};}
export function whatAmIMissing({situation,knownFacts=[],proposedAction}={}){return{tool:'what_am_i_missing',situation:situation||null,knownFacts,proposedAction:proposedAction||null,checks:['Hidden fees or renewals','Cheaper substitute','Missing information','Negotiation leverage','Downside risk']};}
export function getMeABetterDeal({item,askingPrice,targetPrice,alternatives=[],leverage=[]}={}){return{tool:'get_me_a_better_deal',item:item||null,askingPrice:n(askingPrice),targetPrice:n(targetPrice),alternatives,leverage,negotiationPlan:['Establish the all-in price.','Use a defensible target.','Ask directly for the concession.','Set a walk-away point.'],messageTemplate:'I like it, but I am comfortable at [TARGET]. If you can make that work, I am ready to move forward.'};}
export function advocatePlan({goal,facts=[],constraints=[],desiredOutcome}={}){return{tool:'mike_advocate',goal:goal||null,facts,constraints,desiredOutcome:desiredOutcome||null,plan:['Clarify the outcome.','Separate facts from assumptions.','Find leverage and alternatives.','Choose the lowest-risk next action.','Prepare exactly what to say next.']};}
const p=(name,description,properties={},required=[])=>({type:'function',name,description,parameters:{type:'object',properties,required,additionalProperties:false}});
export const MONEY_TOOLS=[p('save_me_money','Find practical ways to reduce a cost.'),p('purchase_affordability','Calculate affordability from supplied facts',{availableCash:{type:'number'},purchaseAmount:{type:'number'},upcomingExpenses:{type:'number'},safetyBuffer:{type:'number'}},['availableCash','purchaseAmount']),p('second_opinion','Structure a second opinion.',{decision:{type:'string'}},['decision']),p('what_am_i_missing','Identify important gaps.',{situation:{type:'string'}},['situation']),p('get_me_a_better_deal','Build a negotiation plan.',{item:{type:'string'}},['item']),p('mike_advocate','Build a user-first action plan.',{goal:{type:'string'}},['goal'])];
export const MONEY_TOOL_HANDLERS={save_me_money:saveMeMoney,purchase_affordability:purchaseAffordability,second_opinion:secondOpinion,what_am_i_missing:whatAmIMissing,get_me_a_better_deal:getMeABetterDeal,mike_advocate:advocatePlan};