import React, { useEffect, useRef, useState } from 'react';
import { Mic, Send, ArrowRight, User, LogOut, X } from 'lucide-react';
import { createRoot } from 'react-dom/client';
import './style.css';

const TOKEN_KEY = 'mike_token';
const readToken = () => { try { return localStorage.getItem(TOKEN_KEY) || ''; } catch { return ''; } };
const writeToken = (token) => { try { if (token) localStorage.setItem(TOKEN_KEY, token); else localStorage.removeItem(TOKEN_KEY); } catch {} };
const authHeaders = () => { const token = readToken(); return token ? { Authorization: `Bearer ${token}` } : {}; };
const fetchJson = async (url, options = {}, timeout = 60000) => { const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), timeout); try { const res = await fetch(url, { ...options, signal: controller.signal }); const data = await res.json().catch(() => ({})); if (!res.ok) { const err = new Error(data.error || `request_failed_${res.status}`); err.status = res.status; throw err; } return data; } finally { clearTimeout(timer); } };
function waitForIceComplete(pc, timeout = 8000) { if (pc.iceGatheringState === 'complete') return Promise.resolve(); return new Promise((resolve) => { let settled = false; const finish = () => { if (settled) return; settled = true; pc.removeEventListener('icegatheringstatechange', check); clearTimeout(timer); resolve(); }; const check = () => { if (pc.iceGatheringState === 'complete') finish(); }; const timer = setTimeout(finish, timeout); pc.addEventListener('icegatheringstatechange', check); }); }

function App() {
  const [messages, setMessages] = useState([{ role: 'mike', text: "What's up? I'm Mike. Tell me what you're trying to figure out. We'll figure it out." }]);
  const [input, setInput] = useState(''); const [busy, setBusy] = useState(false); const [listening, setListening] = useState(false); const [speaking, setSpeaking] = useState(false); const [conversationMode, setConversationMode] = useState(false); const [error, setError] = useState(''); const [user, setUser] = useState(null); const [authOpen, setAuthOpen] = useState(false); const [authMode, setAuthMode] = useState('login'); const [authForm, setAuthForm] = useState({ name: '', email: '', password: '' }); const [authBusy, setAuthBusy] = useState(false); const [authError, setAuthError] = useState(''); const [authNotice, setAuthNotice] = useState(''); const [resetToken, setResetToken] = useState(''); const [accountsOn, setAccountsOn] = useState(false);
  const photoInputRef = useRef(null); const conversationRef = useRef(null); const conversationModeRef = useRef(false); const voiceTransitionRef = useRef(false); const voiceSessionRef = useRef(null);
  const openPhotoPicker = () => photoInputRef.current?.click();
  const settleVoiceSession = async () => { const session = voiceSessionRef.current; if (!session) return; voiceSessionRef.current = null; try { await fetch('/api/speech/session-end', { method: 'POST', headers: { 'Content-Type': 'application/json', ...authHeaders() }, body: JSON.stringify({ sessionKey: session.key, seconds: Math.max(0, Math.round((Date.now() - session.startedAt) / 1000)) }), keepalive: true }); } catch {} };
  const stopRealtimeConversation = async () => { conversationModeRef.current = false; setConversationMode(false); setListening(false); setSpeaking(false); if (conversationRef.current?.close) { try { conversationRef.current.close(); } catch {} } conversationRef.current = null; await settleVoiceSession(); };
  const startRealtimeConversation = async () => { if (voiceTransitionRef.current || !user) { if (!user) setAuthOpen(true); return; } voiceTransitionRef.current = true; setError(''); try { const token = await fetchJson('/api/speech/token', { headers: authHeaders() }, 20000); voiceSessionRef.current = { key: token.sessionKey, startedAt: Date.now() }; conversationModeRef.current = true; setConversationMode(true); setListening(true); } catch (err) { setError(err.message || 'Mike voice is unavailable right now.'); } finally { voiceTransitionRef.current = false; } };
  const toggleConversation = async () => { if (conversationModeRef.current) await stopRealtimeConversation(); else await startRealtimeConversation(); };
  const handlePhotoChange = async (e) => { const file = e.target.files?.[0]; if (!file) return; setError(''); setBusy(true); try { const data = await fetchJson('/api/vision', { method: 'POST', headers: { 'Content-Type': 'application/json', ...authHeaders() }, body: JSON.stringify({ image: await new Promise((resolve, reject) => { const r = new FileReader(); r.onload = () => resolve(String(r.result).split(',')[1]); r.onerror = reject; r.readAsDataURL(file); }) }) }, 60000); setMessages((prev) => [...prev, { role: 'mike', text: data.text || 'I took a look. What do you want to know about it?' }]); } catch (err) { setError(err.message || 'I could not analyze that photo.'); } finally { setBusy(false); e.target.value = ''; } };
  const ask = async (raw) => { const text = (raw || '').trim(); if (!text || busy || conversationModeRef.current) return; setInput(''); setBusy(true); setError(''); const history = messages.slice(-10); setMessages((prev) => [...prev, { role: 'user', text }]); try { const data = await fetchJson('/api/ask', { method: 'POST', headers: { 'Content-Type': 'application/json', ...authHeaders() }, body: JSON.stringify({ message: text, history }) }, 55000); setMessages((prev) => [...prev, { role: 'mike', text: data.text }]); } catch (err) { setError(err.message || 'Mike AI is unavailable right now.'); setMessages((prev) => [...prev, { role: 'mike', text: err.message || 'Mike AI is unavailable right now.' }]); } finally { setBusy(false); } };
  const switchAuthMode = (mode) => { setAuthMode(mode); setAuthError(''); setAuthNotice(''); };
  const submitAuth = async (e) => { e?.preventDefault?.(); if (authBusy) return; setAuthBusy(true); setAuthError(''); setAuthNotice(''); try { if (authMode === 'forgot') { const data = await fetchJson('/api/auth/forgot-password', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email: authForm.email }) }, 20000); setAuthNotice(data.message || 'If that email has an account, a reset link is on its way.'); return; } if (authMode === 'reset') { const data = await fetchJson('/api/auth/reset-password', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ token: resetToken, password: authForm.password }) }, 20000); writeToken(data.token); setUser(data.user); setAuthOpen(false); setResetToken(''); setAuthForm({ name: '', email: '', password: '' }); return; } const path = authMode === 'login' ? '/api/auth/login' : '/api/auth/register'; const body = authMode === 'login' ? { email: authForm.email, password: authForm.password } : authForm; const data = await fetchJson(path, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }, 20000); writeToken(data.token); setUser(data.user); setAuthOpen(false); setAuthForm({ name: '', email: '', password: '' }); } catch (err) { setAuthError(err.message || 'That did not work. Try again.'); } finally { setAuthBusy(false); } };
  const signOut = async () => { await stopRealtimeConversation(); writeToken(''); setUser(null); setMessages([{ role: 'mike', text: "Signed out. I'm still here if you want to talk." }]); };
  useEffect(() => { let cancelled = false; (async () => { try { const health = await fetchJson('/api/health', {}, 10000); if (!cancelled) setAccountsOn(!!health.accountsConfigured); } catch {} if (!readToken()) return; try { const data = await fetchJson('/api/auth/me', { headers: authHeaders() }, 10000); if (!cancelled) setUser(data.user); } catch { writeToken(''); } })(); return () => { cancelled = true; }; }, []);
  useEffect(() => { const params = new URLSearchParams(window.location.search); const token = params.get('reset'); if (!token) return; setResetToken(token); setAuthMode('reset'); setAuthOpen(true); window.history.replaceState({}, '', window.location.pathname); }, []);
  useEffect(() => { const onUnload = () => settleVoiceSession(); window.addEventListener('beforeunload', onUnload); window.addEventListener('pagehide', onUnload); return () => { window.removeEventListener('beforeunload', onUnload); window.removeEventListener('pagehide', onUnload); }; }, []);
  useEffect(() => () => { stopRealtimeConversation(); }, []);
  const statusText = listening ? 'MIKE IS LISTENING' : speaking ? 'MIKE IS TALKING' : busy ? 'MIKE IS THINKING' : 'MIKE IS HERE'; const voiceControlLabel = conversationMode ? 'END CONVERSATION' : 'TAP TO TALK'; const starterPrompts = ['💰 Save me money', 'What would you do?', 'Help me figure this out.', '📷 Ask Mike about a photo'];
  return (<main><header><div className="brand"><b className="brand-dt"><span>D</span><em>T</em></b><div><strong>MIKE AI</strong><small>DOER TOUGH</small></div></div><div className="header-right"><span className="status">● {statusText}</span>{accountsOn && (user ? (<button className="auth-btn" onClick={signOut}><LogOut size={15} /> {user.name.split(' ')[0]}</button>) : (<button className="auth-btn" onClick={() => { setAuthError(''); setAuthOpen(true); }}><User size={15} /> Sign in</button>))}</div></header>
    {authOpen && (() => { const TITLES = { login: 'Welcome back', register: 'Make an account', forgot: 'Reset your password', reset: 'Choose a new password' }; const SUBS = { login: 'Sign in and Mike picks up where you left off.', register: 'So Mike remembers you and your conversations stay yours.', forgot: "Put in your email and we'll send you a link to set a new password.", reset: 'Pick something you have not used elsewhere.' }; const ACTIONS = { login: 'Sign in', register: 'Create account', forgot: 'Send reset link', reset: 'Set new password' }; const showName = authMode === 'register'; const showEmail = authMode !== 'reset'; const showPassword = authMode !== 'forgot'; return (<div className="auth-overlay" role="dialog" aria-modal="true"><div className="auth-card"><button className="auth-close" onClick={() => setAuthOpen(false)}><X size={18} /></button><h2>{TITLES[authMode]}</h2><p className="auth-sub">{SUBS[authMode]}</p><form onSubmit={submitAuth} className="auth-form">{showName && <input placeholder="Your name" value={authForm.name} onChange={(e) => setAuthForm({ ...authForm, name: e.target.value })} />}{showEmail && <input type="email" placeholder="Email" value={authForm.email} onChange={(e) => setAuthForm({ ...authForm, email: e.target.value })} />}{showPassword && <input type="password" placeholder="Password" value={authForm.password} onChange={(e) => setAuthForm({ ...authForm, password: e.target.value })} />}{authError && <div className="auth-error">{authError}</div>}{authNotice && <div className="auth-sub">{authNotice}</div>}<button type="submit" disabled={authBusy}>{authBusy ? 'Working...' : ACTIONS[authMode]}</button></form>{authMode === 'login' && <button className="auth-switch" onClick={() => switchAuthMode('forgot')}>Forgot your password?</button>}<button className="auth-switch" onClick={() => switchAuthMode(authMode === 'register' ? 'login' : authMode === 'login' ? 'register' : 'login')}>{authMode === 'login' ? 'No account yet? Make one.' : authMode === 'register' ? 'Already have an account? Sign in.' : 'Back to sign in'}</button></div></div>); })()}
    <section className="voice-hero"><div className="copy"><label>YOUR EVERYDAY DOER</label><h1>Talk to Mike.<br /><span>Get a straight answer.</span></h1><p>Voice or text, any hour. Price a job, plan your week, talk through a call you have to make, work out what a used truck is really worth. Mike answers like somebody who has done the work — not like a manual.</p><ul className="trust-row"><li>Voice + text</li><li>Cancel anytime</li><li>Mike is here</li></ul><div className="try-row"><span className="try-label">Try him right now</span><div className="try-chips">{starterPrompts.map((prompt) => <button key={prompt} type="button" className="try-chip" onClick={() => prompt.startsWith('📷') ? openPhotoPicker() : ask(prompt)} disabled={busy || conversationMode}>{prompt}</button>)}</div></div></div>
      <div className={'voice-box ' + (listening ? 'is-listening' : speaking ? 'is-speaking' : '')} onClick={toggleConversation} role="button" tabIndex={0}><div className="voice-orb" aria-hidden="true"><span className="orb-core"><span>D</span><em>T</em></span></div><div className="voice-state"><span className="state-dot" /><strong>{statusText}</strong></div><div className="wave" aria-hidden="true">{Array.from({ length: 17 }, (_, i) => <i key={i} style={{ '--delay': `${i * 55}ms`, '--height': `${18 + ((i * 17) % 44)}px` }} />)}</div><p className="voice-hint">{conversationMode ? 'Conversation mode is on.' : 'Tap the mic below when you are ready.'}</p><button className={'voice-puck ' + (conversationMode ? 'active' : '')} onClick={(e) => { e.stopPropagation(); toggleConversation(); }} disabled={voiceTransitionRef.current || busy}><span className="voice-puck-icon"><Mic size={23} /></span><span className="voice-puck-copy"><strong>{voiceControlLabel}</strong><small>{conversationMode ? 'Mike is connected' : 'Press and start talking'}</small></span><ArrowRight className="voice-puck-arrow" size={18} /></button></div></section>
    <section className="chat" aria-live="polite">{messages.map((m, i) => <div key={i} className={'bubble ' + m.role}>{m.text}</div>)}{busy && <div className="bubble mike">Give me a second. I'm thinking…</div>}</section>{error && <div className="error" role="alert">{error}</div>}<input ref={photoInputRef} type="file" accept="image/jpeg,image/png,image/webp" onChange={handlePhotoChange} style={{ display: 'none' }} /><button type="button" className="vision-photo-button" onClick={openPhotoPicker} disabled={busy}>📷 Ask Mike about a photo</button><form onSubmit={(e) => { e.preventDefault(); ask(input); }}><input id="input" value={input} onChange={(e) => setInput(e.target.value)} placeholder="What's on your mind?" autoComplete="off" disabled={conversationMode} /><button disabled={!input.trim() || busy || conversationMode} aria-label="Send"><Send size={18} /></button></form><p className="fine">Mike is a Doer Tough AI assistant. Current facts and changing information should be verified before important decisions.</p></main>);
}
createRoot(document.getElementById('root')).render(<App />);
